{% set name = "ladspa" %}
{% set version = "1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.ladspa.org/download/ladspa_sdk_{{ version }}.tgz
  sha256: 511b237dca0f6c7b993f6be0954215c8f859d6f2a20686b25d082458d763e38b
  patches:
    - Makefile.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('ladspa', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f "${PREFIX}/include/ladspa.h"

about:
  home: https://www.ladspa.org/
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: doc/COPYING
  summary: A standard that allows software audio processors and effects to be plugged into audio synthesis and recording packages
  doc_url: https://www.ladspa.org/ladspa_sdk/overview.html

extra:
  recipe-maintainers:
    - scopatz
